version: '3.8'
services:
  web-server:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_PASSWORD=password
      - MONGO_USER=sebastian
    volumes:
      - ./:/app
      - /app/node_modules

    command: npm run dev